services:
  # Backend Service
  - type: web
    name: blood-donation-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5001
      - key: FRONTEND_URL
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health

  # Frontend Service (Static Site)
  - type: web
    name: blood-donation-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_BASE_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
